spring.application.name=coupon-service

server.port=8080
# Database URL, Username, and Password
spring.datasource.url=jdbc:postgresql://localhost:5432/microservice_db_lab1
spring.datasource.username=postgres
spring.datasource.password=3836

# 'update' will create/modify tables automatically based on your Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Config of Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
